apiVersion: v1
kind: Service
metadata:
  name: practica2-api-service
  namespace: practica2
spec:
  type: NodePort
  selector:
    app: practica2-api
  ports:
    - port: 8080          # Puerto expuesto dentro del cluster
      targetPort: 8080    # Puerto del contenedor de la API .NET
      nodePort: 30080     # Puerto mapeado en tu máquina local